version: "3.5"

services:
  crawler:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    container_name: layerg-crawler
    restart: always
    depends_on:
      - crdb
      - pqdb
    command: "--config config.yaml"
    volumes:
      - ./config.yaml:/go/bin/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: 300m
  api:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    container_name: layerg-api
    restart: always
    depends_on:
      - crdb
      - pqdb
    ports:
      - 8085:8085
    command: "api --config config.yaml"
    volumes:
      - ./config.yaml:/go/bin/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: 300m
  worker:
    image: u2labs/layerg-crawler:latest
    build:
      context: .
    container_name: layerg-worker
    restart: always
    depends_on:
      - crdb
      - pqdb
    command: "worker --config config.yaml"
    volumes:
      - ./config.yaml:/go/bin/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: 300m
  crdb:
    image: cockroachdb/cockroach:v24.2.1
    ports:
      - "26957:26257"
      - "8820:8080"
    command: start-single-node --insecure
    volumes:
      - ../data/crdb:/cockroach/cockroach-data
  pqdb:
    image: postgres:15
    ports:
      - "5492:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: marketplace
    volumes:
      - ../data/pqdb:/var/lib/postgresql/data
  redis:
    image: bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6399:6379"
    volumes:
      - ../redis_data:/bitnami/redis/data
