// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: aawallet.sql

package db

import (
	"context"
	"database/sql"
)

const getAAWalletByAddress = `-- name: GetAAWalletByAddress :one
SELECT id, "userId", type, "uaId", "aaAddress", "factoryAddress", "telegramId", "facebookId", "twitterId", "googleId", "createdAt", "updatedAt", "appKey"
FROM "AAWallet"
WHERE "aaAddress" = $1
`

func (q *Queries) GetAAWalletByAddress(ctx context.Context, aaaddress sql.NullString) (AAWallet, error) {
	row := q.db.QueryRowContext(ctx, getAAWalletByAddress, aaaddress)
	var i AAWallet
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Type,
		&i.UaId,
		&i.AaAddress,
		&i.FactoryAddress,
		&i.TelegramId,
		&i.FacebookId,
		&i.TwitterId,
		&i.GoogleId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppKey,
	)
	return i, err
}
