// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_collection.sql

package db

import (
	"context"
	"database/sql"
)

const addNewAsset = `-- name: AddNewAsset :exec
INSERT INTO assets (
    id, chain_id, collection_address, type, decimal_data, initial_block, last_updated
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, chain_id, collection_address, type, created_at, updated_at, decimal_data, initial_block, last_updated
`

type AddNewAssetParams struct {
	ID                string        `json:"id"`
	ChainID           int32         `json:"chainId"`
	CollectionAddress string        `json:"collectionAddress"`
	Type              AssetType     `json:"type"`
	DecimalData       sql.NullInt16 `json:"decimalData"`
	InitialBlock      sql.NullInt64 `json:"initialBlock"`
	LastUpdated       sql.NullTime  `json:"lastUpdated"`
}

func (q *Queries) AddNewAsset(ctx context.Context, arg AddNewAssetParams) error {
	_, err := q.db.ExecContext(ctx, addNewAsset,
		arg.ID,
		arg.ChainID,
		arg.CollectionAddress,
		arg.Type,
		arg.DecimalData,
		arg.InitialBlock,
		arg.LastUpdated,
	)
	return err
}

const countAssetByChainId = `-- name: CountAssetByChainId :one
SELECT COUNT(*) FROM assets 
WHERE chain_id = $1
`

func (q *Queries) CountAssetByChainId(ctx context.Context, chainID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetByChainId, chainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssetById = `-- name: GetAssetById :one
SELECT id, chain_id, collection_address, type, created_at, updated_at, decimal_data, initial_block, last_updated FROM assets 
WHERE id = $1
`

func (q *Queries) GetAssetById(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetById, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.CollectionAddress,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecimalData,
		&i.InitialBlock,
		&i.LastUpdated,
	)
	return i, err
}

const getPaginatedAssetsByChainId = `-- name: GetPaginatedAssetsByChainId :many
SELECT id, chain_id, collection_address, type, created_at, updated_at, decimal_data, initial_block, last_updated FROM assets 
WHERE chain_id = $1
LIMIT $2 OFFSET $3
`

type GetPaginatedAssetsByChainIdParams struct {
	ChainID int32 `json:"chainId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetPaginatedAssetsByChainId(ctx context.Context, arg GetPaginatedAssetsByChainIdParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, getPaginatedAssetsByChainId, arg.ChainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.CollectionAddress,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecimalData,
			&i.InitialBlock,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
