// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: onchain_history.sql

package db

import (
	"context"
	"time"
)

const addOnchainTransaction = `-- name: AddOnchainTransaction :one
INSERT INTO 
    onchain_histories("from","to",asset_id,token_id,amount,tx_hash,timestamp)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, "from", "to", asset_id, token_id, tx_hash, timestamp, created_at, updated_at, amount
`

type AddOnchainTransactionParams struct {
	From      string    `json:"from"`
	To        string    `json:"to"`
	AssetID   string    `json:"assetId"`
	TokenID   string    `json:"tokenId"`
	Amount    string    `json:"amount"`
	TxHash    string    `json:"txHash"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) AddOnchainTransaction(ctx context.Context, arg AddOnchainTransactionParams) (OnchainHistory, error) {
	row := q.db.QueryRowContext(ctx, addOnchainTransaction,
		arg.From,
		arg.To,
		arg.AssetID,
		arg.TokenID,
		arg.Amount,
		arg.TxHash,
		arg.Timestamp,
	)
	var i OnchainHistory
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.AssetID,
		&i.TokenID,
		&i.TxHash,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
	)
	return i, err
}

const getOnchainHistoriesByTxHash = `-- name: GetOnchainHistoriesByTxHash :many
SELECT id, "from", "to", asset_id, token_id, tx_hash, timestamp, created_at, updated_at, amount FROM onchain_histories WHERE tx_hash = $1
`

func (q *Queries) GetOnchainHistoriesByTxHash(ctx context.Context, txHash string) ([]OnchainHistory, error) {
	rows, err := q.db.QueryContext(ctx, getOnchainHistoriesByTxHash, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnchainHistory
	for rows.Next() {
		var i OnchainHistory
		if err := rows.Scan(
			&i.ID,
			&i.From,
			&i.To,
			&i.AssetID,
			&i.TokenID,
			&i.TxHash,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
