// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_history.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const upsertOrderHistory = `-- name: UpsertOrderHistory :exec
INSERT INTO "OrderHistory" (id, index, sig, nonce, "fromId", "toId", "qtyMatch", price, "priceNum", timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT ("sig", "index") DO NOTHING
`

type UpsertOrderHistoryParams struct {
	ID        uuid.UUID      `json:"id"`
	Index     int32          `json:"index"`
	Sig       string         `json:"sig"`
	Nonce     sql.NullString `json:"nonce"`
	FromId    uuid.UUID      `json:"fromId"`
	ToId      uuid.UUID      `json:"toId"`
	QtyMatch  int32          `json:"qtyMatch"`
	Price     string         `json:"price"`
	PriceNum  float64        `json:"priceNum"`
	Timestamp int32          `json:"timestamp"`
}

func (q *Queries) UpsertOrderHistory(ctx context.Context, arg UpsertOrderHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrderHistory,
		arg.ID,
		arg.Index,
		arg.Sig,
		arg.Nonce,
		arg.FromId,
		arg.ToId,
		arg.QtyMatch,
		arg.Price,
		arg.PriceNum,
		arg.Timestamp,
	)
	return err
}
